blueprint:
  name: Motion and Actived Lights (Humidity)
  description: Turn on a light or light group when motion is detected. Keep light on if humidity is above a threshold.
  domain: automation
  source_url: https://github.com/nbar1/ha-blueprints/blob/main/automation/lights-by-motion-and-humidity.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 60
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    humidity_sensor_entity:
      name: Humidity Sensor
      selector:
        entity:
          domain: sensor
          device_class: humidity
    humidity_threshold:
      name: Humidity Threshold
      description: Humidity threshold to keep the light on.
      default: 75
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: percent
          step: 1.0
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: 'off'
    to: 'on'

action:
  - alias: Turn on the light
    service: light.turn_on
    target: !input light_target
  - alias: Wait until there is no motion from device
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: 'on'
      to: 'off'
  - alias: Wait the number of seconds that has been set
    delay: !input no_motion_wait
  - alias: Check humidity level
    wait_for_trigger:
      platform: numeric_state
      entity_id: !input humidity_sensor_entity
      above: !input humidity_threshold
  - alias: Turn off the light
    service: light.turn_off
    target: !input light_target
